In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt

In [127]:
def KernlPCA(train_x,test_x,n):
    print("Train_X", train_x)
    from sklearn.decomposition import KernelPCA
    kpca = KernelPCA(n_components = n, kernel = 'rbf')
    train_x = kpca.fit_transform(train_x)
    test_x = kpca.transform(test_x)

    return train_x, test_x #lda_features

In [91]:
def split_scalar(indep_X,dep_Y):
        train_x, x_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        train_x = sc.fit_transform(train_x)
        test_x = sc.transform(x_test)    
        return train_x, test_x, y_train, y_test

In [93]:
def cm_prediction(classifier,X_test):
     y_pred = classifier.predict(X_test)
        
        # Making the Confusion Matrix
     from sklearn.metrics import confusion_matrix
     cm = confusion_matrix(y_test, y_pred)
        
     from sklearn.metrics import accuracy_score 
     from sklearn.metrics import classification_report
        
     Accuracy=accuracy_score(y_test, y_pred )
        
     report=classification_report(y_test, y_pred)
     return classifier,Accuracy,report,X_test,y_test,cm

In [95]:
def logistic(X_train,y_train,X_test):       
        # Fitting K-NN to the Training set
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train, y_train)
        classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
        return classifier,Accuracy,report,X_test,y_test,cm

In [97]:
def svm_linear(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'linear', random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [99]:
def svm_NL(X_train,y_train,X_test):
    from sklearn.svm import SVC
    classifier = SVC(kernel = 'rbf', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [100]:
def Navie(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.naive_bayes import GaussianNB
    classifier = GaussianNB()
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [103]:

def knn(X_train,y_train,X_test):
    from sklearn.neighbors import KNeighborsClassifier
    classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p=2)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [105]:
def Decision(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.tree import DecisionTreeClassifier
    classifier = DecisionTreeClassifier(criterion  = 'entropy',random_state = 0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm



In [107]:
def random(X_train,y_train,X_test):
    # Fitting K-NN to the Training set
    from sklearn.ensemble import RandomForestClassifier
    classifier = RandomForestClassifier(n_estimators = 10, criterion ='entropy', random_state =0)
    classifier.fit(X_train,y_train)
    classifier,Accuracy,report,X_test,y_test,cm=cm_prediction(classifier,X_test)
    return classifier,Accuracy,report,X_test,y_test,cm

In [109]:
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['Kernal_PCA'],columns=['Logistic','SVMl','SVMNl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        # df.loc[row_indexer, "col"] = values
        dataframe.loc[idex,'Logistic']=acclog[number]
        dataframe.loc[idex,'SVMl']=accsvml[number]
        dataframe.loc[idex,'SVMNl']=accsvmnl[number]
        dataframe.loc[idex,'KNN']=accknn[number]
        dataframe.loc[idex,'Navie']=accnav[number]
        dataframe.loc[idex,'Decision']=accdes[number]
        dataframe.loc[idex,'Random']=accrf[number]
        # print(dataframe)
        # dataframe['Logistic'][idex]=acclog[number]       
       # dataframe['SVMl'][idex]=accsvml[number]
        # dataframe['SVMnl'][idex]=accsvmnl[number]
        # dataframe['KNN'][idex]=accknn[number]
        # dataframe['Navie'][idex]=accnav[number]
        # dataframe['Decision'][idex]=accdes[number]
        # dataframe['Random'][idex]=accrf[number]
    return dataframe

In [111]:

# Importing the dataset
dataset = pd.read_csv('Social_Network_Ads.csv')
df2=dataset.copy()
df2

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19.0,19000.0,0
1,15810944,Male,35.0,20000.0,0
2,15668575,Female,26.0,43000.0,0
3,15603246,Female,27.0,57000.0,0
4,15804002,Male,19.0,76000.0,0
...,...,...,...,...,...
395,15691863,Female,46.0,41000.0,1
396,15706071,Male,51.0,23000.0,1
397,15654296,Female,50.0,20000.0,1
398,15755018,Male,36.0,33000.0,0


In [113]:

df2 = pd.get_dummies(df2, drop_first=True)
df2

,User ID,Age,EstimatedSalary,Purchased,Gender_Male
0,15624510,19.0,19000.0,0,True
1,15810944,35.0,20000.0,0,True
2,15668575,26.0,43000.0,0,False
3,15603246,27.0,57000.0,0,False
4,15804002,19.0,76000.0,0,True
...,...,...,...,...,...
395,15691863,46.0,41000.0,1,False
396,15706071,51.0,23000.0,1,True
397,15654296,50.0,20000.0,1,False
398,15755018,36.0,33000.0,0,True


In [115]:
X = df2.iloc[:, [2, 3]].values
Y = df2.iloc[:, 4].values

In [117]:
X

array([[1.90e+04, 0.00e+00],
       [2.00e+04, 0.00e+00],
       [4.30e+04, 0.00e+00],
       [5.70e+04, 0.00e+00],
       [7.60e+04, 0.00e+00],
       [5.80e+04, 0.00e+00],
       [8.40e+04, 0.00e+00],
       [1.50e+05, 1.00e+00],
       [3.30e+04, 0.00e+00],
       [6.50e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [5.20e+04, 0.00e+00],
       [8.60e+04, 0.00e+00],
       [1.80e+04, 0.00e+00],
       [8.20e+04, 0.00e+00],
       [8.00e+04, 0.00e+00],
       [2.50e+04, 1.00e+00],
       [2.60e+04, 1.00e+00],
       [2.80e+04, 1.00e+00],
       [2.90e+04, 1.00e+00],
       [2.20e+04, 1.00e+00],
       [4.90e+04, 1.00e+00],
       [4.10e+04, 1.00e+00],
       [2.20e+04, 1.00e+00],
       [2.30e+04, 1.00e+00],
       [2.00e+04, 1.00e+00],
       [2.80e+04, 1.00e+00],
       [3.00e+04, 1.00e+00],
       [4.30e+04, 0.00e+00],
       [1.80e+04, 0.00e+00],
       [7.40e+04, 0.00e+00],
       [1.37e+05, 1.00e+00],
       [1.60e+04, 0.00e+00],
       [4.40e+04, 0.00e+00],
       [9.00e+

In [119]:
train_x, test_x, y_train, y_test=split_scalar(X,Y) 

In [129]:
X_train, X_test=KernlPCA(train_x,test_x,4)       
acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

Train_X [[-0.88670699 -0.76635604]
 [ 1.46173768  1.30487651]
 [-0.5677824  -0.76635604]
 [ 1.89663484  1.30487651]
 [-1.40858358  1.30487651]
 [ 0.99784738  1.30487651]
 [-0.79972756 -0.76635604]
 [-0.24885782 -0.76635604]
 [-0.5677824  -0.76635604]
 [-0.19087153 -0.76635604]
 [-1.29261101 -0.76635604]
 [-0.5677824  -0.76635604]
 [ 0.09905991  1.30487651]
 [-0.59677555  1.30487651]
 [-1.17663843  1.30487651]
 [-0.13288524 -0.76635604]
 [ 1.78066227  1.30487651]
 [ 0.56295021 -0.76635604]
 [ 0.35999821 -0.76635604]
 [-0.53878926  1.30487651]
 [-1.58254245 -0.76635604]
 [ 0.93986109  1.30487651]
 [ 1.22979253 -0.76635604]
 [ 1.08482681  1.30487651]
 [-0.48080297 -0.76635604]
 [-0.30684411 -0.76635604]
 [-0.8287207   1.30487651]
 [ 1.8676417   1.30487651]
 [ 1.25878567  1.30487651]
 [ 2.27354572  1.30487651]
 [-1.58254245 -0.76635604]
 [-0.79972756  1.30487651]
 [-1.46656987 -0.76635604]
 [ 2.30253886  1.30487651]
 [ 0.76590222 -0.76635604]
 [-0.30684411 -0.76635604]
 [ 0.76590222  1.304

In [131]:
X_train

array([[-0.39041115,  0.36445519, -0.35037262,  0.05368696],
       [ 0.77830581, -0.3816688 , -0.36108476, -0.03358735],
       [-0.47518026,  0.15909208, -0.181593  ,  0.07688893],
       ...,
       [-0.48509309,  0.11777864, -0.14702015,  0.07741766],
       [-0.49304559,  0.0759756 , -0.11189001,  0.07667906],
       [ 0.06097905, -0.35997039,  0.25630816, -0.32000923]])

In [133]:
X_test

array([[-0.32857955, -0.43935707,  0.32809491, -0.10065727],
       [-0.47518026,  0.15909208, -0.181593  ,  0.07688893],
       [-0.44812601, -0.31749158,  0.22366622, -0.006947  ],
       [-0.41428502, -0.36894177,  0.2678775 , -0.03595291],
       [-0.47518026,  0.15909208, -0.181593  ,  0.07688893],
       [-0.17584111,  0.55219018, -0.48951186, -0.03460519],
       [-0.11745754,  0.55897669, -0.48844397, -0.05940585],
       [ 0.66776283, -0.32951514, -0.40867215, -0.48534029],
       [-0.48918832, -0.20458725,  0.12672671,  0.03530416],
       [-0.42651628,  0.29550374, -0.29442919,  0.06574406],
       [-0.46951756,  0.17946925, -0.1985863 ,  0.07616147],
       [-0.49626124,  0.05498759, -0.09420149,  0.07582526],
       [-0.49626124,  0.05498759, -0.09420149,  0.07582526],
       [-0.4320697 , -0.34451019,  0.24688819, -0.02108004],
       [-0.34037119, -0.43298705,  0.32268959, -0.09226228],
       [ 0.05035728, -0.3680015 ,  0.26314205, -0.3157145 ],
       [-0.4320697 , -0.

In [135]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train,y_train,X_test)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train,y_train,X_test)  
accsvml.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train,y_train,X_test)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train,y_train,X_test)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train,y_train,X_test)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train,y_train,X_test)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train,y_train,X_test)  
accrf.append(Accuracy)

In [137]:
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)


In [88]:
result
#6

,Logistic,SVMl,SVMNl,KNN,Navie,Decision,Random
Kernal_PCA,1.0,1.0,1.0,1.0,1.0,0.977778,1.0


In [100]:
result
#5

,Logistic,SVMl,SVMNl,KNN,Navie,Decision,Random
Kernal_PCA,1.0,1.0,1.0,1.0,1.0,0.955556,1.0


In [77]:
result
#1

,Logistic,SVMl,SVMNl,KNN,Navie,Decision,Random
Kernal_PCA,0.5,0.49,0.45,0.5,0.49,0.57,0.53


In [65]:
result
#2

,Logistic,SVMl,SVMNl,KNN,Navie,Decision,Random
Kernal_PCA,0.45,0.49,0.5,0.56,0.48,0.6,0.55
