In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
independent

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']]
dependent

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [29]:
from sklearn.preprocessing import StandardScaler
scx=StandardScaler()
x_input=scx.fit_transform(independent)
x_input

array([[-1.43876426, -0.45332   , -0.90861367, -1.0105187 ,  1.97058663],
       [-1.50996545,  0.5096211 , -0.07876719,  0.98959079, -0.5074631 ],
       [-0.79795355,  0.38330685,  1.58092576,  0.98959079, -0.5074631 ],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367, -1.0105187 , -0.5074631 ],
       [-1.29636188, -0.79781341, -0.90861367, -1.0105187 , -0.5074631 ],
       [ 1.55168573, -0.26138796, -0.90861367, -1.0105187 ,  1.97058663]])

In [33]:
scy=StandardScaler()
y_output=scy.fit_transform(dependent)
y_output

array([[ 0.2985838 ],
       [-0.95368917],
       [-0.72867467],
       ...,
       [-0.96159623],
       [-0.93036151],
       [ 1.31105347]])

In [35]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid'],
              'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(x_input, y_output)

Fitting 5 folds for each of 30 candidates, totalling 150 fits


C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid']},
             verbose=3)

In [37]:
# print best parameter after tunng
# print(grid.best_params_)
re = grid.cv_results_
# print(re)
print("The r_value for best parameter{}:".format(grid.best_params_))

The r_value for best parameter{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}:


In [39]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0        0.404550      0.038614         0.044372        0.026836       10   
1        1.053044      0.095944         0.009195        0.000748       10   
2        0.191926      0.007253         0.028605        0.000463       10   
3        0.319602      0.020824         0.030981        0.001094       10   
4        1.081754      0.132086         0.009194        0.001468       10   
5        0.188147      0.005555         0.028983        0.001548       10   
6        1.534101      0.238770         0.032247        0.001341      100   
7        9.206830      1.320847         0.009553        0.001222      100   
8        0.192598      0.007430         0.028573        0.000519      100   
9        1.515329      0.248194         0.033980        0.004772      100   
10       8.647665      1.056976         0.008384        0.000499      100   
11       0.184086      0.003185         0.028193        0.000395      100   
12      12.297312      2.324449         0.037702        0.005195     1000   
13     106.630524     22.911177         0.008395        0.000490     1000   
14       0.192407      0.005280         0.029373        0.001338     1000   
15      13.389933      3.458107         0.039776        0.004487     1000   
16      85.686725     12.956775         0.009995        0.000883     1000   
17       0.187937      0.006687         0.028992        0.001257     1000   
18      25.279312      2.789019         0.042814        0.006268     2000   
19     176.560978     31.080379         0.008298        0.000401     2000   
20       0.194479      0.005710         0.028880        0.000803     2000   
21      23.399026      2.722800         0.037292        0.003738     2000   
22     182.159429     25.083953         0.009595        0.001020     2000   
23       0.202355      0.009909         0.034986        0.005312     2000   
24      41.115401      5.946855         0.058071        0.041934     3000   
25     258.476953     43.664535         0.013494        0.007753     3000   
26       0.231777      0.012861         0.031791        0.001932     3000   
27      40.371742      4.831883         0.071067        0.058988     3000   
28     259.730154     63.470776         0.009194        0.001600     3000   
29       0.192081      0.009574         0.028183        0.000748     3000   

   param_gamma param_kernel  \
0         auto          rbf   
1         auto         poly   
2         auto      sigmoid   
3        scale          rbf   
4        scale         poly   
5        scale      sigmoid   
6         auto          rbf   
7         auto         poly   
8         auto      sigmoid   
9        scale          rbf   
10       scale         poly   
11       scale      sigmoid   
12        auto          rbf   
13        auto         poly   
14        auto      sigmoid   
15       scale          rbf   
16       scale         poly   
17       scale      sigmoid   
18        auto          rbf   
19        auto         poly   
20        auto      sigmoid   
21       scale          rbf   
22       scale         poly   
23       scale      sigmoid   
24        auto          rbf   
25        auto         poly   
26        auto      sigmoid   
27       scale          rbf   
28       scale         poly   
29       scale      sigmoid   

                                               params  split0_test_score  \
0         {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}       8.774642e-01   
1        {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}       8.554449e-01   
2     {'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}      -7.207321e+03   
3        {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}       8.774173e-01   
4       {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}       8.553904e-01   
5    {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}      -6.535274e+03   
6        {'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}       8.562076e-01   
7       {'C': 100, 'gamma': 'auto', 'kernel': 

In [41]:
age=float(input("AGE:"))
bmi=float(input("BMI:"))
children=float(input("Children:"))
gender=int(input("Gender Male 0 or 1:"))
smoker=int(input("Smoker Yes 0 or 1 :"))

AGE: 32
BMI: 43
Children: 2
Gender Male 0 or 1: 0
Smoker Yes 0 or 1 : 1


In [43]:
Prediction=grid.predict([[age,bmi,children,gender,smoker]])
print("Future Predocion{}".format(Prediction))

Future Predocion[0.50845085]


In [45]:
Prediction=grid.predict([[32,43,2,0,1]])
Prediction

array([0.50845085])